kind: pipeline
name: default

steps:
- name: docker
  image: thegeeklab/drone-docker-buildx:23
  privileged: true
  settings:
    username: uzurka
    password: 
      from_secret: docker_password
    repo: uzurka/freebox-telegraf
    tags: latest
    platforms: 
      - linux/amd64
      - linux/arm64
      - linux/arm/v7