kind: pipeline
name: default

steps:
- name: docker
  image: thegeeklab/drone-docker-buildx:23
  privileged: true
  settings:
    username: dynaloo
    password: 
      from_secret: ${{ secrets.DOCKERHUB }}
    repo: dynaloo13/freebox-telegraf
    tags: latest
    platforms: 
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
