{
 "title": "Freebox POP",
 "description": "Monitoring Freebox POP with InfluxDB v2 and Grafana",
 "tags": [
  "InfluxDB v2",
  "Freebox"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Infos générales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Debit synchro",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"box\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"mafreebox.freebox.fr\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"down\" or r[\"tag2\"] == \"up\")\r\n  |> last()\r\n  |> group(columns: [\"_measurement\"])\r\n  |> keep(columns: [\"tag2\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Trafic total",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"box\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"down\" or r[\"tag2\"] == \"up\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"mafreebox.freebox.fr\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> last()\r\n  |> group(columns: [\"_measurement\"])\r\n  |> keep(columns: [\"_value\", \"tag2\"])\r\n  "
    }
   ]
  },
  {
   "title": "Statut Signal Fibre & Addresse",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"box\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sfp_has_signal\" or r[\"_field\"] == \"ipv4\" or r[\"_field\"] == \"ipv6\" or r[\"_field\"] == \"media\")\r\n  |> group(columns: [\"_measurement\", \"tag1\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"media\", \"ipv4\", \"ipv6\",\"sfp_has_signal\"])"
    }
   ]
  },
  {
   "title": "Freebox",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"System\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pretty_name\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"System\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"firmware_version\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Freebox Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"System\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "suffix:ko/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"box\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"down\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\r\n  |> map(fn: (r) => ({r with _value: (r._value / 125.0) / 8.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "suffix:ko/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"box\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"up\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\r\n  |> map(fn: (r) => ({r with _value: (r._value / 125.0) / 8.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Switch Ports Mode",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Switch\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Etat\" or r[\"_field\"] == \"mode\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"link#1\" or r[\"tag2\"] == \"link#2\" or r[\"tag2\"] == \"link#3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> keep(columns: [\"tag2\", \"Etat\", \"mode\"])\r\n\r\n   \r\n\r\n"
    }
   ]
  },
  {
   "title": "Equipements connectés",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"hosts_list\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"primary_name\" or r[\"_field\"] == \"active\" or r[\"_field\"] == \"addr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"primary_name\", \"active\", \"addr\"])"
    }
   ]
  },
  {
   "title": "Température",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag3\"] == \"temp_cpub\" or r[\"tag3\"] == \"temp_t1\" or r[\"tag3\"] == \"temp_t2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ventilation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Fan\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Graphiques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Switch Freebox (Port 1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Rx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Tx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#1\")\r\n  |> map(fn: (r) => ({r with _value: r._value / -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Switch Freebox (Port 2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Rx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Tx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#2\")\r\n  |> map(fn: (r) => ({r with _value: r._value / -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Switch Freebox (Port 3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Rx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"Tx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rate\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"Port#3\")\r\n  |> map(fn: (r) => ({r with _value: r._value / -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Freebox Port Fibre",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"down\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"up\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\r\n  |> map(fn: (r) => ({r with _value: r._value / -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wifi Freebox",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"wifi_list\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_rate\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"5G\" or r[\"tag2\"] == \"24G\")\r\n  |> group(columns: [\"tag1\", \"_field\", \"_measurement\", \"tag2\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"wifi_list\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_rate\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"5G\" or r[\"tag2\"] == \"24G\")\r\n  |> group(columns: [\"tag1\", \"_field\", \"_measurement\", \"tag2\"])\r\n  |> map(fn: (r) => ({r with _value: r._value / -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Equipements connectés Wifi 2.4G",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"24G\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"primary_name\" or r[\"_field\"] == \"active\" or r[\"_field\"] == \"addripv4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  \r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"primary_name\", \"active\", \"addripv4\"])"
    }
   ]
  },
  {
   "title": "Equipements connectés Wifi 5G",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"freebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"freebox\")\r\n  |> filter(fn: (r) => r[\"tag2\"] == \"5G\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"primary_name\" or r[\"_field\"] == \"active\" or r[\"_field\"] == \"addripv4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  \r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"primary_name\", \"active\", \"addripv4\"])"
    }
   ]
  }
 ]
}