
###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################
             
# Configuration for sending metrics to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://Your_IP_InfluxDB2:8086"]
  token = "Your_Token_InfluxDB2"
  organization = "Organization_Name_in_your_InfluxDB2 "
  bucket = "freebox" # Bucket_name_created_in_your_InfluxDB2 - Why not "freebox"

###############################################################################
#                            INPUT PLUGINS FREEBOX                            #
###############################################################################
        
# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
## Commands array
#
# API freebox OS V8
  commands = [
    "python3 /usr/local/py/freebox_061.py -SPHDIWXYZ4" # Or "freebox_070.py" which is latest version
]
        
## Timeout for each command to complete.
timeout = "8s"
        
## Data format to consume.
## Each data format has it's own unique set of configuration options, read
## more about them here:
## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
# data_format = "graphite"

data_format = "influx"

