
###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################
             
# Configuration for sending metrics to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://192.168.1.34:8086"]
  token = "vKKD0Gdi7Bztck0q5aXISZONPMTKoSNYtIa_M3fsrpqXaY4krrryg9Sh7ue7hW-ZBErXqDt3oPnD0bYiI3gSjw=="
  organization = "monitoring"
  bucket = "freebox"

###############################################################################
#                            INPUT PLUGINS FREEBOX                            #
###############################################################################
        
# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
## Commands array
#
# API freebox OS V8
  commands = [
                 "python3 /usr/local/py/freebox_061.py -SPHDIWXYZ4"
]
        
## Timeout for each command to complete.
timeout = "8s"
        
## Data format to consume.
## Each data format has it's own unique set of configuration options, read
## more about them here:
## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
# data_format = "graphite"
data_format = "influx"