on: [push]

jobs:
  hello_world_job:
    runs-on: debian-latest
    name: test
    steps:
      - name: freebox action step
        id: freefox
        uses: actions/dynallo/monitoring-freebox-action@test
        with:
          who-to-greet: 'eric'
      # Use the output from the `freebox` step
