name: Docker Image Freebox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: publish
      run: |
        docker login -u dynaloo13 -p ${{ secrets.DOCKERHUB }}
        docker push dynaloo13/freebox-telegraf:v1.0.1