name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: dynaloo13/freebox-telegraf/dockerhub-description@v4
      with:
        username: ${{ secrets.USER_DOCKER_HUB }}
        password: ${{ secrets.DOCKER_HUB }}
        repository: dynaloo13/freebox-telegraf
        short-description: Telegraf pour serveur Freebox
        enable-url-completion: true