name: Docker Image Freebox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build Docker freebox
      run: docker build . -t dynaloo13/freebox-telegraf:v1.0.1
    - name: publish docker hub
      run: |
        docker login -u dynaloo13 -p ${{ secrets.DOCKERHUB }}
        docker push dynaloo13/freebox-telegraf:v1.0.1