name: Docker Build/push image Freebox

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/docker-image.yml'
      - 'telegraf.conf'
      - 'freebox-monit.py'
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: open the docker socket
        run: sudo chmod 666 /var/run/docker.sock

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.DOCKERHUB }}

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag dynaloo13/freebox-telegraf:latest \
            --tag dynaloo13/freebox-telegraf:${{ github.sha }} \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --push \
            . 
