kind: pipeline
name: default

steps:
- name: docker
  image: thegeeklab/drone-docker-buildx:23
  privileged: true
  settings:
    username:
    password: 
      from_secret: docker_password
    repo: dynaloo/monitoring-freebox
    tags: latest
    platforms: 
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
