name: Docker Push README

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker Push README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          docker login -u dynaloo13 -p ${{ secrets.DOCKERHUB }}
        with:
          destination_container_repo: dynaloo13/freebox-telegraf
          provider: dockerhub
          short_description: 'Monitoring Freebox'
          readme_file: 'README.md'
