name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.USER_DOCKER_HUB }}
        password: ${{ secrets.DOCKERHUB }}
        repository: dynaloo13/dockerhub-description
        short-description: Telegraf pour serbeur Freebox
        enable-url-completion: true