name: Publish freebox image

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t dynaloo13/freebox-telegraf:v.1.0
      - name: publish
        run: |
          docker login -u dynaloo13 -p ${{ secrets.DOCKERHUB }}
          docker push dynaloo13/freebox-telegraf:v.1.0
